name: CICD
on:
  push:
    branches:
    - '*'
jobs:
  build:
    name: build flutter
    runs-on: macos-11
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: camt-flutter-5506
          channelId: live